[TOKENS]
# API Key generated for the Lucid API. You can create these at https://lucid.app/developer/apikeys
# The key will need the following grants for the base functionality of this script. 
# # Teams: Admin - Access to create and modify any team on your account. Requires Team Admin role at a minimum
# # Account: Readonly - Access to read basic information about users on your account
# If the configuration includes a custom folder structure you will also need
# # User: View - Access to read profile information about this user
# # Folder: Edit - Access to read and create Lucid folders that this user has access to
KEY=key-YWE0NzZiMWFkMzAwZG....

[FILES]
# Location of the CSV file where this script will pull in configuration information for the teams
TEAM_CSV_FILEPATH=lucid_teams_single_test.csv

# If config is defined it will be used to instantiate all newly created teams with the folder structure defined in the JSON file
# The general json structure will be of the following
# [
#   {
#      "name": "FolderName",
#      "subFolders": [
#           {
#               "name": "SubFolderName",
#               "subFolders": [...]
#           },
#       ]
#   },
# ]
FOLDER_STRUCTURE_FILEPATH=folder_structure.json

[FLAGS]
# Determines if users on existing teams changed by this API should be removed or remain
REMOVE_EXISTING_USERS=false

# Determines if the script should attempt to read a JSON file containing default folder structure for the teams
CREATE_FOLDER_STRUCTURE=false